/*---------------------------------------------------------------------------------------
--	SOURCE FILE:		file_svr.c -   A simple file transfer server using TCP
--
--	PROGRAM:		fsvr.exe (?)
--
--	FUNCTIONS:		Berkeley Socket API
--
--	DATE:			September 27, 2016
--
--	REVISIONS:		N/A
--
--	DESIGNERS:		Aicha Hezit
--
--	PROGRAMMERS:		Aicha Hezit
--
--	NOTES:
--	The program will accept TCP connections from client machines.
-- 	The program will recieve commands from the client socket and eihter send or 
-- 	recieve a file back.
---------------------------------------------------------------------------------------*/
